Quote column names to avoid conflict with psql identiifers (#1)
* Quote column names to avoid conflict with psql identiifers

If the column we are journaling contains columns which are keywords in
psql (e.g. 'primary'), then the command to create the journal trigger
will fail.

Example:

tmp=# create table tmp (id text primary key, "primary" boolean);
CREATE TABLE

tmp=# select journal.refresh_journaling('public', 'tmp', 'journal', 'tmp');

   ERROR:  syntax error at or near "primary"
   LINE 1: ...  insert into journal.tmp (journal_operation, id, primary) v...

* Update table comment

* fix