Upgrade journal
  - Remove assumption on an 'id' column. Instead, query the source
    table for all of the columns in its primary key index, if one
    exists, and then create an index on the same set of columns on the
    journal table. This fixes https://github.com/gilt/db-journaling/issues/12

  - remove old.*, new.* and replace with explicit column lists. This
    prevents the runtime error when adding a column to the source
    table which we think is a better failure mode.

  - add defaults for parameters in the journal.refresh_journal_trigger function

    This allows for the default case of using the same table name in
    the journal schema to omit the target schema and table names

  - for columns of character data types, use the type 'text' in the journal
    tables. This avoids complications around sizing / resizing of these fields.
    Convert 'character', 'character varying', and '"char"' types.
    Fixes https://github.com/gilt/db-journaling/issues/1

  - When creating journal table, set columns that are part of the
    primary key to not null. This will cause potential errors if you
    alter the source table's primary key - but we feel this is rarely
    needed and in those cases we can expect the journal to be
    recreated.

  - add a check to prevent changes to primary key values. The primary
    key values are the only pieces of data we have in the journal to
    tie the records together. If you change the value of a primary key
    column, you lose the ability to read the journal coherently. Thus
    we add assertions into the trigger that the primary key values are
    unchanged.

    An example of the error message a user will receive in this case:

    ERROR: Table[public.users] is journaled. Updates to primary key
    column[guid] are not supported as this would make it impossible to
    follow the history of this row in the journal table[journal.users]